export const MessageConstant = {
    DIALOG_TITLE_SUCCESSFULLY: 'Successfully',
    DIALOG_TITLE_WARNING: 'Warning',
    DIALOG_TITLE_ERROR: 'Error',
    DIALOG_TITLE_CONFIRMATION: 'Confirmation',
    ERROR_REQUIRED_FIELD: 'You can\'t leave this blank.',
    ERROR_REQUIRED_ATTACHMENT: 'Attachment is required',
    ERROR_VALID_URL: 'You must insert valid URL',
    MESSAGE_SAVE_SUCCESSFULLY: 'Save Successfully',
    MESSAGE_SAVE_FAIL: 'Save Fail',
    MESSAGE_UPDATE_SUCCESSFULLY: 'Update Successfully',
    MESSAGE_UPDATE_FAIL: 'Update Fail',
    MESSAGE_DELETE_SUCCESS: 'Delete Successfully',
    MESSAGE_HINT_VALID_URL: 'Example: http://example.com',
    MESSAGE_CONFIRM_DELETE_AAP_ITEM: 'Delete AAP Item?',
    MESSAGE_CONFIRM_DELETE_ACTION_ITEM: 'Delete Action Item?',
    MESSAGE_CONFIRM_DELETE_ASSURANCE_PLAN_ITEM: 'Delete Assurance Plan Item?',
    MESSAGE_CONFIRM_DELETE_DEPARTMENT_AAP_ITEM: 'Delete Department AAP Item?',
    MESSAGE_CONFIRM_DELETE_ACTION_ITEM_PROGRESS: 'Delete Action Item Progress?',
    MESSAGE_CONFIRM_DELETE_FINDING_ITEM: 'Delete Finding Item?',
    MESSAGE_CONFIRM_DELETE_ASSESSOR: 'Are You Sure Delete Assessor?',
    ERROR_NUMBEROFPLAN_FIELD: 'Value should be equal or greater than default value.',
    ERROR_NUMBEROFQUATERLYPLAN_FIELD: 'Value of quater should be equal no of plan.',
};
