// <auto-generated />
namespace Elearn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DB_eLearn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_eLearn));
        
        string IMigrationMetadata.Id
        {
            get { return "201803301605134_DB_eLearn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
